export default{
    MUSIC_PLAY:'MUSIC_PLAY',
    MUSIC_PAUSE:'MUSIC_PAUSE',
    MUSIC_QUERY:'MUSIC_QUERY',
    MUSIC_QUERYED:'MUSIC_QUERYED',
    UPDATE_TIME:'UPDATE_TIME',
    UPDATE_DURATION:'UPDATE_DURATION',
    UPDATE_STATUS:'UPDATE_STATUS'
}